apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  annotations:
#    field.cattle.io/creatorId: user-g2sjq
#    field.cattle.io/ingressState: '{"a2V5cm9jay9maXdhcmUveGlwLmlvLy8vMzAwMA==":""}'
#    field.cattle.io/publicEndpoints: '[{"addresses":["\u003cnil\u003e"],"port":80,"protocol":"HTTP","serviceName":"fiware:keyrockserv","ingressName":"fiware:keyrock","hostname":"keyrock.fiware.30.0.0.2.xip.io","path":"/","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: keyrock
  selfLink: /apis/extensions/v1beta1/namespaces/fiware/ingresses/keyrock
spec:
  rules:
  - host: keyrock.fiware.30.0.0.2.xip.io
    http:
      paths:
      - backend:
          serviceName: keyrockserv
          servicePort: 30050
        path: /
status:
  loadBalancer: {}
